default:
	@echo venv
	@echo build
	@echo test
	@echo create


venv:
	@echo source /Users/paul/github/slexil2/py3105slexil/bin/activate

build:
	m4 try1.pre > try1.html


test:
	python test_yamlToCyJSON.py

create:
	python createGraph.py demo.yaml
